use std::{collections::HashMap, fmt::Write};

use crate::{
    abi::{Amd64ABI, XenABI},
    spec::{AbiSpec, CType, HypercallOp},
};

fn emit_register_variable<ABI: XenABI>(
    w: &mut impl Write,
    id: u8,
    value: Option<&str>,
) -> anyhow::Result<()> {
    write!(
        w,
        "    register {ctype} reg{id} __asm__(\"{reg}\")",
        ctype = if id == 0 { "long" } else { "uint64_t" },
        reg = ABI::get_register_name(id)
    )?;
    if let Some(value) = value {
        write!(w, " = {value}")?;
    }
    writeln!(w, ";")?;

    Ok(())
}

fn emit_hypercall<ABI: XenABI>(
    w: &mut impl Write,
    op: &HypercallOp,
    ident: usize,
    instruction: &str,
) -> anyhow::Result<()> {
    let start = format!("{:ident$}__asm__ volatile (\"{instruction}\" ", "");
    let pad = start.len();

    /* All the exclusive inputs. */
    let reg_input = op
        .input
        .right_values()
        .filter(|&input| !op.output.contains_right(input))
        .map(|input| format!("\"r\"(reg{input})"))
        .collect::<Box<[_]>>()
        .join(", ");

    /* Outputs that are also inputs are transformed into +r, the rest is =r */
    let reg_output = op
        .output
        .right_values()
        .chain(&[0]) /* 0 is always a input/output */
        .map(|output| {
            if *output == 0 || op.input.contains_right(output) {
                format!("\"+r\"(reg{output})")
            } else {
                format!("\"=r\"(reg{output})")
            }
        })
        .collect::<Box<[_]>>()
        .join(", ");

    writeln!(w, "{:ident$}{start}: {reg_output}", "")?;
    writeln!(w, "{:ident$}{:pad$}: {reg_input}", "", "")?;
    writeln!(w, "{:ident$}{:pad$}: \"memory\");", "", "")?;

    Ok(())
}

fn generate_hypercall_function(
    w: &mut impl Write,
    hypercall_name: &str,
    op: &HypercallOp,
    function_name: &str,
    subop_index: Option<u32>,
) -> anyhow::Result<()> {
    writeln!(w, "static inline")?;

    eprintln!("Processing {hypercall_name}.{function_name}");
    let annotations = op.c_lang.clone().unwrap_or_default();

    assert!(
        annotations.cstruct.is_some() || op.output.is_empty(),
        "struct-less wrappers doesn't allow outputs, please use a C structure"
    );

    // Match each input register with its C value.
    let input_map: HashMap<u8, String> = op
        .input
        .iter()
        .map(|(name, &id)| {
            if annotations.params.contains_key(name) {
                (id, name.clone())
            } else {
                // Struct may have a custom mapping
                let field = annotations.mapping.get(name).unwrap_or(name);

                (id, format!("param->{field}"))
            }
        })
        .collect();

    write!(w, "long {function_name}(enum xen_hypercall_vendor vendor")?;
    let pad = 6 + function_name.len();

    if let Some(cstruct) = &annotations.cstruct {
        write!(w, ",\n{:pad$}struct {cstruct} *param", "",)?;
    }

    for (name, CType(ctype)) in &annotations.params {
        write!(w, ",\n{:pad$}{ctype} {name}", "",)?;
    }

    writeln!(w, ")")?;

    writeln!(w, "{{")?;

    for id in op.used_registers() {
        // If it is a input, we need to set it here.
        let value = match (id, subop_index) {
            /* Hypercall index */
            (0, _) => Some(format!(
                "__HYPERVISOR_FASTABI_MASK | __HYPERVISOR_{hypercall_name}_op"
            )),
            /* Sub-operation index */
            (1, Some(subop_index)) => Some(format!("{subop_index}")),
            /* Other input parameter */
            (id, _) => input_map.get(&id).cloned(),
        };

        emit_register_variable::<Amd64ABI>(w, id, value.as_deref())?;
    }
    writeln!(w)?;

    writeln!(w, "    if ( vendor == Intel )")?;
    emit_hypercall::<Amd64ABI>(w, op, 4, "vmcall")?;
    writeln!(w, "    else")?;
    emit_hypercall::<Amd64ABI>(w, op, 4, "vmmcall")?;

    writeln!(w, "")?;

    for (field, output) in &op.output {
        let field = annotations.mapping.get(field).unwrap_or(field);

        writeln!(w, "    param->{field} = reg{output};")?;
    }

    writeln!(w, "    return reg0;")?;

    writeln!(w, "}}")?;

    Ok(())
}

pub fn generate_code(w: &mut impl Write, spec: AbiSpec) -> anyhow::Result<()> {
    writeln!(w, "/* SPDX-License-Identifier: MIT */")?;
    writeln!(w, "/* AUTOGENERATED. DO NOT MODIFY */")?;
    writeln!(w)?;

    if let Some(op) = spec.direct {
        let function_name = ["xen_hypercall", &spec.name].join("_");

        generate_hypercall_function(w, &spec.name, &op, &function_name, None)?;
        writeln!(w)?;
    }

    for (name, mut subop) in spec.subops {
        let function_name = ["xen_hypercall", &spec.name, &name].join("_");
        subop.op.input.insert("subop_index".to_string(), 1);

        generate_hypercall_function(w, &spec.name, &subop.op, &function_name, Some(subop.index))?;
        writeln!(w)?;
    }

    Ok(())
}
